module.exports.descriptors = [
    'Contemporary',
    'Cosmopolitan',
    'Wandering',
    'Crafty',
    'Bittersweet',
    'Pleasent',
    'Silent',
    'Secluded',
    'Hidden',
    'Traveling',
    'Misty',
    'Forgotten',
    'Forbidden',
    'Ocean',
    'Sinful',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Inn',
    'Tavern',
    'Pond',
    'Pub',
    'Speakeasy',
    'Bar',
    'Canteen',
    'Counter',
    'Saloon',
    'Taproom',
    'Lounge',
    'Gin mill',
    'Hostelry',
    'Cocktail lounge',
    'Boozer',
    'Shed',
    'Drinkery',
    'Hotel',
    'Ale house',
    'Corner'
]
